Implement rate limiting for nginx proxies
salt-formulas/salt-formula-nginx pull request #34
Opened 2018-03-13 13:04 UTC by mnederlof

This implements specifically:
- General rate limit possibility on IP basis
- Specific rate limit on URL with different rate

In our usecase we see a lot of k8s environments that query the nova API every 20 seconds for every instance. This creates quite some load on the platform (e.g. neutron) and should be prevented, as this causes the platform to slowdown.

2018-03-13 14:46 UTC, jakubjosef requested changes
Please use spaces after {{ and }}.

2018-03-13 17:18 UTC, mnederlof commented
@jakubjosef, I changed the format, anything else required?

2018-04-09 14:06 UTC, jakubjosef approved these changes

2018-04-09 15:10 UTC, epcim approved these changes
sees ok to me

2018-04-09 15:16 UTC, merged