Proxy locations
salt-formulas/salt-formula-nginx pull request #36
Opened 2018-03-14 08:52 UTC by stelucz

Actual implementation is missing possibility of defining multiple location parts.

2018-03-19 09:53 UTC, fpytloun requested changes

2018-03-19 09:53 UTC, fpytloun commented on README.rst
> +              locations:
This key should be singular, `location:`

2018-03-19 09:53 UTC, fpytloun commented on nginx/server/sites.sls
> +  {%- elif site.type == 'nginx_proxy_locations' %}
Why do you need to add new site type instead of extending `nginx_proxy`?

2018-03-19 09:53 UTC, fpytloun commented on nginx/files/proxy_locations.conf
> +  ssl_session_cache shared:SSL:10m;
This should go to `_ssl.conf`

2018-03-20 08:05 UTC, stelucz commented
Hello @fpytloun,
thanks for comments. Intention of adding a new site type is to keep 100% backwards compatibility with existing models. If you think that it is better to extend existing `nginx_proxy` type, let me know your idea on how you would like to see it implemented. :)
Thanks!

2018-03-20 08:06 UTC, stelucz commented on nginx/files/proxy_locations.conf
> +  ssl_session_cache shared:SSL:10m;
thus `proxy.conf` should be patched too

2018-03-20 10:01 UTC, fpytloun commented
Yes, I would prefer extending proxy type instead of defining new one. There's a lot of duplicated options.
I suggest to have something like:
```
{%- set location = {} %}
{%- if site.get('location') %}
{%- do location.update(site.location) %}
{%- else %}
{# Default / location #}
{%- do location.update({'/': {'enabled': True}})
{%- endif %}
```

in proxy.conf and iterate over it in a similar fashion as you do in proxy_location

2018-03-20 20:28 UTC, stelucz commented
@fpytloun 
I did changes so `proxy.conf` is extended now. Locations are generated from `location:` part. 
1. If `location` part is not present in model, then `proxy` part is used.
1. If `/` location is not defined in `location` and `proxy` part is in model then `proxy` is used.
1. if `/` location and `proxy` is defined, then `/` location is used (overrides `proxy` definition)
 
I removed `ssl_session_cache`  from `_ssl_secure.conf` and `proxy.conf` as it's already defined in `_ssl.conf`

Let me know if change looks good to you or wish some other edits. Thanks!

2018-03-21 14:18 UTC, fpytloun requested changes
Yes, it looks much better now.

2018-03-21 14:18 UTC, fpytloun commented on README.rst
> +            type: nginx_proxy_locations
Should be nginx_proxy

2018-03-21 14:18 UTC, fpytloun commented on README.rst
> +            type: nginx_proxy_locations
same here

2018-03-21 14:19 UTC, fpytloun commented on nginx/files/proxy.conf
> +  {%- if site.get('location', False) %}
FYI: .get defaults to something evaluated as false so you don't need to explicitly use False as a default value

2018-03-21 15:15 UTC, stelucz commented
@fpytloun Thanks, it should be fixed now.

2018-03-26 08:18 UTC, stelucz commented
@fpytloun Hi, does it look ok?

2018-03-26 08:23 UTC, fpytloun commented
Looks good to me now, thank you :)

2018-03-26 08:23 UTC, merged

2018-03-26 08:44 UTC, stelucz commented
Thank you too! 
Have a nice week.